# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 092b5b501e3b968d8c8f89141304fd262c2afb1f219cabe8d2c27f033440c89eefb94fd11158c5fdc6b014c3e1e1a1c4745cfea618027660a258193aa1741fe2

test:
  secret_key_base: 213e96a0f9138ba6c479d01eca2c3a6b944e0095a1243a69af1cdd3901987e7677946d1bf7b4ba57a305fd334d396e325246e486b36f2ec9f91149a21551a8c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
